#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const libDir = resolve(__dirname, '../src/lib');

function load(file) {
  const raw = readFileSync(resolve(libDir, file), 'utf8');
  const words = raw
    .split(/\r?\n/)
    .map((w) => w.trim().toLowerCase())
    .filter((w) => /^[a-z]{5}$/.test(w));
  return [...new Set(words)].sort();
}

const answers = load('words.txt');
const guesses = load('guesses.txt');
const valid = [...new Set([...answers, ...guesses])].sort();

const header = `// AUTO-GENERATED by scripts/build-words.mjs — do not edit by hand.
// Source: src/lib/words.txt (answers), src/lib/guesses.txt (extra valid guesses).
// Regenerate with: npm run build:words
`;

const body = `${header}
export const ANSWER_WORDS: readonly string[] = ${JSON.stringify(answers)};

export const VALID_WORDS: ReadonlySet<string> = new Set(${JSON.stringify(valid)});
`;

const outPath = resolve(libDir, 'words.generated.ts');
writeFileSync(outPath, body);

console.log(
  `wrote ${outPath}\n  answers: ${answers.length}\n  valid:   ${valid.length}`,
);
